### ISSUE TITLE
Add automatic dates at the end of QC report

### ISSUE THREAD

**Issue by Sal4321** [FredHutch/VISCtemplates#244]
This is a feature update request which is close to #181 . Can we modify visc_pdf_document function to add an automatic date at the output file so that we don't have to manually add dates everytime we generate a qc report ? Note that we add dates at the end of qc report when we are sending qc reports to the lab. The modification might look something like this:

```
visc_pdf_document <- function(latex_engine = "pdflatex",
                              keep_tex = TRUE,
                              ...) {
  template <- find_resource("visc_report", "template.tex")

  logo_path_scharp <- find_resource("visc_report", "SCHARP_logo.png")
  logo_path_fh <- find_resource("visc_report", "FredHutch_logo.png")
  logo_path_visc <- find_resource("visc_report", "VISC_logo.jpg")

  # If no project-level bib file creating report specific bib
  if (!file.exists(here::here('docs', 'bibliography.bib'))) {
    file.copy(from = system.file("templates", 'bibliography.bib',
                                 package = "VISCtemplates"),
            to = "bibliography.bib",
            overwrite = FALSE)
   }

  file.copy(from = find_resource("visc_report", "README_PT_Report.md"),
            to = "README.md",
            overwrite = FALSE)

  # Get the current date in the desired format (e.g., YYYY-MM-DD)
  current_date <- format(Sys.Date(), "%Y-%m-%d")

  # Append the date to the output file name
  rmarkdown::render(input = "inputfile", output_file = paste("outputFile",current_date))
  bookdown::pdf_document2(
    template = template,
    keep_tex = keep_tex,
    fig_caption = TRUE,
    latex_engine = latex_engine,
    pandoc_args = c(
      "-V", paste0("logo_path_scharp=", logo_path_scharp),
      "-V", paste0("logo_path_fh=", logo_path_fh),
      "-V", paste0("logo_path_visc=", logo_path_visc)
    )
    ...)
}
```

I can also suggest how to incorporate it properly here after some tests

**Comment by slager** [comment]
There was some discussion this week, and the consensus was that we will think about putting dated QC reports into a separate folder to help organize `data-raw/`, but probably not implement auto-adding dates to QC reports, since 1) having a date manually added denotes it was manually sent to the lab, and 2) we often re-knit QC reports repeatedly during development, and wouldn't really want to have intermediate reports under development being given automatic dates on each unique day we're working on them.  Closing this as "unplanned" for now but this generated some very useful discussion, thanks @Sal4321.

**Comment by Sal4321** [comment]
Thanks @slager for putting the  summary of the discussions !
