### ISSUE TITLE
Incorporate Alicia's guidance on PT report naming into package

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCtemplates#98]
```
I’d like to propose a naming convention for PT report RMDs, which would include some basic identifying information. Here’s my proposal:
VDCPI-cvdnum_assay_PT_Report_blindingstatusifapplicable.Rmd
where assay is the subfolder name and blindingstatusifapplicable is used if there are blinded and unblinded reports generated.
For example,
Dubois846_BAMA_PT_Report.Rmd
Hassell750_NAB_PT_Report_blinded.Rmd
```

**Comment by kelliemac** [comment]
Guidance on whether or not to include a batch descriptor (example: "highdose") would also be helpful

**Comment by kelliemac** [comment]
@asatofh can you please review this and let us know if you are happy with the format that Monica described above, or if you would propose any changes?

**Comment by asatofh** [comment]
> @asatofh can you please review this and let us know if you are happy with the format that Monica described above, or if you would propose any changes?

I forgot about this! Yes, this format makes sense and reflects what Monica and I had discussed. The only change I'd make is to use "interim" and "final" instead of "blinded" and "unblinded", since we are doing more unblinded interim PT reports, and the interim vs final seems like a more important distinction since this reflects the folder structure. We could include both, e.g., "interim_blinded" - tagging @mayerbry so he can weigh in if needed.

**Comment by mayerbry** [comment]
small suggestion: don't use PT_report (use PT-report or PTreport) as the _ might be useful as a parsing character into key words describing the report
